version: 2
updates:
  # Maven dependencies
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "deps"
      include: "scope"
    reviewers:
      - "jwcarman"
    # Group updates by dependency type
    groups:
      spring:
        patterns:
          - "org.springframework*"
        update-types:
          - "minor"
          - "patch"
      testing:
        patterns:
          - "org.junit*"
          - "org.assertj*"
          - "org.mockito*"
          - "org.testcontainers*"
        update-types:
          - "minor"
          - "patch"
      build-plugins:
        patterns:
          - "org.apache.maven.plugins*"
          - "org.jacoco*"
          - "org.sonarsource*"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "ci"
      include: "scope"
    reviewers:
      - "jwcarman"
